### ISSUE TITLE
AWS 키 관련 .gitignore 작성 

### ISSUE THREAD

**Issue by chaeheekang** [pinetree2/terraform-study#1]
[terraform.tfvars](https://github.com/pinetree2/terraform-study/blob/main/terraform.tfvars)
AWS 접근에 관여하는 키는 .gitignore 파일 작성을 해서 github에 직접적으로 올리지 말기~ 
[참고](https://github.com/cloud-club/cc3_season2_Terraform/blob/main/Architecture1/%EC%B1%84%ED%9D%AC/AWS/.gitignore)

**Comment by pinetree2** [comment]
고맙뜸다
